### ISSUE TITLE
[Feature Request] support torch 1.14

### ISSUE THREAD

**Issue by nan2088** [apache/tvm-ffi#381]
AttributeError: module 'torch' has no attribute 'uint16'

```
root@xxx:/workspace/# pip install apache-tvm-ffi
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting apache-tvm-ffi
  Downloading apache_tvm_ffi-0.1.7-cp38-cp38-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 814 kB/s 
Collecting typing-extensions>=4.5
  Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 72.7 MB/s 
Installing collected packages: typing-extensions, apache-tvm-ffi
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 4.4.0
    Uninstalling typing-extensions-4.4.0:
      Successfully uninstalled typing-extensions-4.4.0
Successfully installed apache-tvm-ffi-0.1.7 typing-extensions-4.13.2

>>> import tvm_ffi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tvm_ffi/__init__.py", line 40, in <module>
    from .registry import (
  File "/usr/local/lib/python3.8/dist-packages/tvm_ffi/registry.py", line 25, in <module>
    from . import core
  File "python/tvm_ffi/cython/dtype.pxi", line 183, in init tvm_ffi.core
AttributeError: module 'torch' has no attribute 'uint16'```

**Comment by junrushao** [comment]
I believe @oraluben has more data, but my understanding is that it supports very old PyTorch versions like 2.4, which even PyTorch doesn't officially maintain. For even older ones, we are more than happy to accept patches and bugfixes, but with no promise to continuously test it.

**Comment by oraluben** [comment]
`torch.uint16` has been added in torch==2.3.0, both 2.3 and 2.4 works with tvm-ffi 0.1.7. Personally I'd like tvm-ffi to support all torch>=2.0, but there might be not much value to support 1.x?

as a data point: we're dealing with torch==2.4.0 as a minimal support version for our scenario.

**Comment by nan2088** [comment]
Some dirty work in real-world scenarios has to be dealt with in our case.   One workaround when the torch version is 1.x is to allows tvm_ffi to be imported smoothly with TVM_FFI_DISABLE_TORCH_C_DLPACK=1. This part would be relatively easy to fix. We can then consider follow-up fixes for addons. We would like to contribute some patches later.

**Comment by junrushao** [comment]
@nan2088 Sounds like a good idea

**Comment by junrushao** [comment]
Closed via #414. Thanks again @nan2088 for contributing!

**Comment by oraluben** [comment]
Just noticed there's more places we need to take care of if we want to support torch < 2.4:

`DeviceType::MAIA` is introduced in torch 2.4, and jit dlpack ext will fail for earlier version torch.

https://github.com/apache/tvm-ffi/blob/761966953fec7e8ceba0fcc20dc003e39cf2692d/python/tvm_ffi/utils/_build_optional_torch_c_dlpack.py#L164-L165
