### ISSUE TITLE
[Bug] Wheel works with 0.1.0 does not work with 0.1.4

### ISSUE THREAD

**Issue by oraluben** [apache/tvm-ffi#307]
Update by @junrushao: See https://github.com/apache/tvm-ffi/issues/307#issuecomment-3613877612 for an investigation report.

------------------------------------------------------------------------------------------------

Error with a linux arm wheel of tilelang, when upgrading tvm-ffi:

```
$ python -c 'import tilelang'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.12/site-packages/tilelang/__init__.py", line 99, in <module>
    import tvm
  File "/venv/lib/python3.12/site-packages/tilelang/3rdparty/tvm/python/tvm/__init__.py", line 27, in <module>
    from .base import TVMError, __version__, _RUNTIME_ONLY
  File "/venv/lib/python3.12/site-packages/tilelang/3rdparty/tvm/python/tvm/base.py", line 58, in <module>
    _LIB, _LIB_NAME = _load_lib()
                      ^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/tilelang/3rdparty/tvm/python/tvm/base.py", line 45, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /venv/lib/python3.12/site-packages/tilelang/lib/libtvm.so: undefined symbol: __cxa_call_terminate
```

> Looks like the missing `__cxa_call_terminate` is that tvm-ffi 0.1.4 has been compiled with gcc prior to 14: https://stackoverflow.com/questions/79815074/linking-fails-with-in-function-main-cold-undefined-reference-to-cxa-call
> 
> This can be validated with the linux-arm wheel from: https://github.com/tile-ai/tilelang/actions/runs/19888262788?pr=1373
> 
> `python -c 'import tilelang'` works with `apache-tvm-ffi==0.1.0`, and failed with `apache-tvm-ffi==0.1.4`

By default, manylinux_2_28 uses gcc 14.

Update:
this is wrong:

> tvm-ffi 0.1.4 has been compiled with gcc prior to 14

It works for tvm-ffi <= 0.1.1, does work for >= 0.1.2 and building from source.

Update 2: bisect to https://github.com/apache/tvm-ffi/pull/240, which looks totally irrelevant 🤨 it somehow lost the dependency to libstdc++?

Original comment: 
https://github.com/tile-ai/tilelang/pull/1373#issuecomment-3605445597

**Comment by tqchen** [comment]
thanks, to understand the state, it seems was due to our wheel on arm was using older version of manylinux that is not `manylinux_2_28`?

**Comment by tqchen** [comment]
note that the latest version comes with https://github.com/apache/tvm-ffi/blob/main/.github/workflows/publish_wheel.yml#L39C1-L40C1

both manylinux 2_28 wheel and manylinux 2014 wheel, can you explicitly check which wheel is being installed? I think manylinux2_28 wheel should be OK.

Maybe we should consider static link stdc++ and hide symbols for maximum portability

**Comment by junrushao** [comment]
Re-post [my response](https://github.com/tile-ai/tilelang/pull/1373#issuecomment-3608159427) in the other thread:

> Looks like the missing `__cxa_call_terminate` is that tvm-ffi 0.1.4 has been compiled with gcc prior to 14: https://stackoverflow.com/questions/79815074/linking-fails-with-in-function-main-cold-undefined-reference-to-cxa-call
> 
> This can be validated with the linux-arm wheel from: https://github.com/tile-ai/tilelang/actions/runs/19888262788?pr=1373
> 
> `python -c 'import tilelang'` works with `apache-tvm-ffi==0.1.0`, and failed with `apache-tvm-ffi==0.1.4`
> 
> cc @junrushao

Just to confirm - which wheel are you using btw? I checked tvm-ffi's manylinux_2_28 wheel, and it's indeed built with GCC >= 14

```
  -- The CXX compiler identification is GNU 14.2.1
  -- The C compiler identification is GNU 14.2.1
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /opt/rh/gcc-toolset-14/root/usr/bin/g++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /opt/rh/gcc-toolset-14/root/usr/bin/gcc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detected target triple: x86_64-redhat-linux
  -- Setting C++ macro TVM_FFI_USE_LIBBACKTRACE - 1
  -- Setting C++ macro TVM_FFI_BACKTRACE_ON_SEGFAULT - 1
  -- Building cython module..
  -- Found Python: /tmp/build-env-vxg1ktop/bin/python (found version "3.14.0") found components: Interpreter Development.Module Development.SABIModule

```

**Comment by junrushao** [comment]
Wait. The warning comes from libtvm instead of libtvm_ffi. Do you think there might be some issue in tvm building?

**Comment by oraluben** [comment]
It's not related to manylinux, even if I built latest tvm-ffi from source, it still don't work. (See updated comment above)

Now I think it would be a minor mismatch between tvm that tilelang uses and tvm-ffi, I'll validate today.

**Comment by junrushao** [comment]
Can you please double check how libtvm.so is built and which libstdcxx it is linked against?

**Comment by oraluben** [comment]
The issue disappeared after manually applied #240 to the bundled tvm-ffi that tilelang's tvm uses, that being said, the change somehow introduced ABI changes under gcc 14?

The tilelang issue would be solved after it upgrades to a newer version of tvm so it's not blocking, please feel free to close this issue.
For tvm-ffi, I suggest to add a test that checks the symbol it reference/uses to be stable for each release.

**Comment by junrushao** [comment]
Cross posting @oraluben's findings here: https://github.com/tile-ai/tilelang/pull/1373#issuecomment-3610109098

**Comment by junrushao** [comment]
Here's what ChatGPT says:

---------------------------------

Short version: that PR moved all the “potentially‑throwing string work” *out* of a `noexcept` function and into a normal function. With GCC 14 that’s exactly what toggles whether the compiler emits a reference to `__cxa_call_terminate`, so the symbol set of `libtvm_ffi.so` changes before vs. after the PR.

---

### What PR #240 actually changed

From the mail-archive diff of tvm-ffi PR #240, the key changes in `include/tvm/ffi/error.h` are: ([[Mail Archive](https://www.mail-archive.com/commits%40tvm.apache.org/msg116566.html)][1])

1. **Introduced `Error::FullMessage()`**:

```cpp
std::string FullMessage() const {
  ErrorObj* obj = static_cast<ErrorObj*>(data_.get());
  return (std::string("Traceback (most recent call last):\n") +
          TracebackMostRecentCallLast() +
          std::string(obj->kind.data, obj->kind.size) + std::string(": ") +
          std::string(obj->message.data, obj->message.size) + '\n');
}
```

This builds the full traceback + kind + message, using a bunch of `std::string` operations that can allocate and therefore **can throw**.

2. **Changed `Error::what()` to a trivial “just return pointer” implementation**:

```cpp
const char* what() const noexcept(true) override {
  ErrorObj* obj = static_cast<ErrorObj*>(data_.get());
  return obj->message.data;
}
```

Before the PR, the implementation of `what()` itself *built* that full string:

```cpp
const char* what() const noexcept(true) override {
  thread_local std::string what_data;
  ErrorObj* obj = static_cast<ErrorObj*>(data_.get());
  what_data = (std::string("Traceback (most recent call last):\n") +
               TracebackMostRecentCallLast() +
               std::string(obj->kind.data, obj->kind.size) +
               std::string(": ") +
               std::string(obj->message.data, obj->message.size) + '\n');
  return what_data.c_str();
}
```

3. **`ErrorBuilder::~ErrorBuilder()` still throws, but now logs via `FullMessage()` instead of `what()`**:

```cpp
[[noreturn]] ~ErrorBuilder() noexcept(false) {
  ::tvm::ffi::Error error(std::move(kind_), stream_.str(), std::move(backtrace_));
  if (log_before_throw_) {
    std::cerr << error.FullMessage();  // previously error.what()
  }
  throw error;
}
```

So the *signature* of the destructor and of `what()` didn’t change in this patch (the destructor was already `noexcept(false)`); what changed is **where the string-building work lives**.

---

### How that affects `__cxa_call_terminate`

GCC 14 introduced a new runtime helper `__cxa_call_terminate()` in libstdc++ to implement the behavior “a `noexcept` function let an exception escape → call `std::terminate()`.” If you compile code with GCC 14 that has a `noexcept` function whose body *may throw*, the compiler emits a reference to this symbol. Older libstdc++ doesn’t have it, which is why mixing GCC 14–compiled code with older libstdc++ leads to undefined‑reference / undefined‑symbol errors. ([[Stack Overflow](https://stackoverflow.com/questions/79815074/linking-fails-with-in-function-main-cold-undefined-reference-to-cxa-call)][2])

Now look at the two versions:

* **Before PR #240**
  `Error::what()` is declared `noexcept(true)` and its body constructs a `std::string` using concatenation and `TracebackMostRecentCallLast()`. All of those `std::string` operations are *not* `noexcept`, so from the compiler’s point of view, `what()` is a `noexcept` function containing potentially-throwing code.

  Under GCC 14, that combination (noexcept + potentially-throwing) triggers generation of code which, if an exception propagates out of `what()`, calls `__cxa_call_terminate`. That makes `__cxa_call_terminate` show up as an imported symbol of `libtvm_ffi.so`.

* **After PR #240**
  `what()` still has the `noexcept(true)` signature, but its body is now just:

  ```cpp
  ErrorObj* obj = static_cast<ErrorObj*>(data_.get());
  return obj->message.data;
  ```

  These operations are trivially non-throwing (no allocations, no `std::string` operations, no explicit `throw`). The compiler can now *prove* that `what()` cannot throw, so it no longer needs to generate any “if an exception escapes, call terminate” path, and therefore it no longer emits a reference to `__cxa_call_terminate` from this function.

  The heavy string-building logic moved into `FullMessage()`, which is **not declared `noexcept`**, and is called from a destructor that is also `noexcept(false)`. Exceptions are allowed to propagate normally there, so no `__cxa_call_terminate` is needed.

That’s why, when you compare `libtvm_ffi.so` built from before vs. after PR #240 (with GCC 14), `grep -nr __cxa_call_terminate` shows a change in the symbol set: the pre‑PR library references `__cxa_call_terminate`, the post‑PR one doesn’t. ([[Mail Archive](https://www.mail-archive.com/commits%40tvm.apache.org/msg116566.html)][1])

---

### How this relates to your `undefined symbol: __cxa_call_terminate`

Putting it together with your original failure:

* Your `libtvm.so` (from TileLang) depends on `libtvm_ffi.so`, which in turn is built from tvm-ffi >= 0.1.2 that incorporates PR #240 or nearby changes, using GCC 14’s toolchain. ([[GitHub](https://github.com/apache/tvm-ffi/issues/307)][3])
* On your runtime system, the `libstdc++.so.6` that gets loaded is **older** and doesn’t provide `__cxa_call_terminate`.
* If your particular tvm-ffi wheel still references `__cxa_call_terminate` (e.g., built just before PR #240, or from other code paths), the dynamic loader can’t resolve that symbol and you see:

  ```text
  OSError: ... libtvm.so: undefined symbol: __cxa_call_terminate
  ```

After PR #240, once everything is rebuilt with it, the `Error::what()` path no longer requires `__cxa_call_terminate`, so that particular dependency goes away and the symptom can disappear—even though the *root* mismatch (GCC 14 vs. older libstdc++) is still there.

---

### Practical implication

So the contributor’s observation:

> the symbol of libtvm_ffi.so itself changes before and after that PR, you can check by `grep -nr __cxa_call_terminate`

is spot on: the change in how `Error::what()` is implemented moves potentially-throwing code out of a `noexcept` function, and that’s exactly what turns the `__cxa_call_terminate` reference on or off in the compiled shared library.

If you want to be fully robust:

* Make sure **all** the C++ pieces (tvm-ffi, tvm, tilelang) are built against the same libstdc++ ABI version, or
* Stick to a tvm-ffi version/wheel that doesn’t end up referencing `__cxa_call_terminate` on your platform, or
* Upgrade your runtime libstdc++ to one that includes `__cxa_call_terminate` (the GCC‑14 era libstdc++). ([[Stack Overflow](https://stackoverflow.com/questions/79815074/linking-fails-with-in-function-main-cold-undefined-reference-to-cxa-call)][2])

But the specific “why did the symbol in libtvm_ffi.so change before/after that PR?” is: **because PR #240 moved throwing string operations out of a `noexcept` function, so GCC 14 stopped emitting the `__cxa_call_terminate` path for it.**

[1]: https://www.mail-archive.com/commits%40tvm.apache.org/msg116566.html "(tvm-ffi) branch main updated: [ERROR] Make Error conform more to std (#240)"
[2]: https://stackoverflow.com/questions/79815074/linking-fails-with-in-function-main-cold-undefined-reference-to-cxa-call "c++ - Linking fails with: in function `main.cold': undefined reference to `__cxa_call_terminate' - Stack Overflow"
[3]: https://github.com/apache/tvm-ffi/issues/307 "[Bug] Wheel works with 0.1.0 does not work with 0.1.4 · Issue #307 · apache/tvm-ffi · GitHub"

**Comment by junrushao** [comment]
Please follow my digging w/ @oraluben in tilelang thread: https://github.com/tile-ai/tilelang/pull/1373

**Comment by junrushao** [comment]
@oraluben and I did some digging, and let me debrief what’s going on under the hood.

**Observation**. Missing symbol `__cxa_call_terminate` raises from libtvm.so (libtvm.so is part of TileLang distro), when built against certain tvm-ffi versions. Specifically,
* ✅ apache-tvm-ffi 0.1.0
* ❌ apache-tvm-ffi 0.1.4

**What does `_cxa_call_terminate` do**. This symbol is part of higher version of libstdc++ runtime, specifically, it's introduced in CXXABI_1.3.15 in libstdc++ when the library SONAME was bumped to libstdc++.so.6.0.33.

GCC >= 14 generates call into libstdc++’s symbol `_cxa_call_terminate` when exceptions are raised inside a noexcept method, which essentially calls `std::terminate`. tvm-ffi wheels are always built in manylinux_2_28 using GCC 14. 

**Does libtvm_ffi.so require this symbol**? No in principle. However, in reality, before #240, it is needed as the noexcept method `what()` uses `std::string`, which could throw and leads GCC 14 to generate calling to this symbol. #240 fixes this issue as part of 0.1.4 release.

Did a little digging into libtvm_ffi.so, and it shows:
- v0.1.0 contains `_cxa_call_terminate` in its text section ("T")
- v0.1.4 doesn't have `_cxa_call_terminate`

**Why is `_cxa_call_terminate` in text section?** Toolchain gcc-toolset-14 in manylinux_2_28 provides libstdc++.so as a ld script:

```
>>> cat /opt/rh/gcc-toolset-14/root/usr/lib/gcc/x86_64-redhat-linux/14/libstdc++.so
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library, so try that secondarily.  */
OUTPUT_FORMAT(elf64-x86-64)
INPUT ( /usr/lib64/libstdc++.so.6 -lstdc++_nonshared AS_NEEDED (/usr/lib64/libstdc++.so.6) )
```

which, will bring in symbols from `/opt/rh/gcc-toolset-14/root/usr/lib/gcc/x86_64-redhat-linux/14/libstdc++_nonshared.a` upon symbol missing.

In this case, the symbol `_cxa_call_terminate` is indeed missing from `/usr/lib64/libstdc++.so.6`, and the linker brings it into `libtvm_ffi.so` per request. That explains why v0.1.0 has this symbol in its text section.

**Does libtvm.so needs this symbol**? It's unclear to me. This symbol is needed if one throws in a noexcept method, which is extremely rare in TVM codebase AFAICT. If it does have such behaviors and the behavior is intended, one will need a higher version of libstdc++.so which has this symbol.

**Explain the crash**.

- ✅ libtvm.so doesn't crash w/ tvm-ffi v0.1.0 - because libtvm_ffi.so happens to have `_cxa_call_terminate` defined in text section
- ❌ libtvm.so crashes w/ tvm-ffi v0.1.4 - because libtvm_ffi.so fixes it bug in PR #240, and no longer carries `_cxa_call_terminate` with it

**Comment by junrushao** [comment]
Closing this issue as no bugfix is required according to our investigation. It's an interesting digging experience.
