### ISSUE TITLE
[Bug] NPE since 0.1.8

### ISSUE THREAD

**Issue by oraluben** [apache/tvm-ffi#464]
with `>=0.1.8`, the original issue https://github.com/apache/tvm/issues/18798 no longer raise readable error message. It crash with following error message:

```
python(69796,0x1f328ec40) malloc: *** error for object 0x8000000000000070: pointer being freed was not allocated
python(69796,0x1f328ec40) malloc: *** set a breakpoint in malloc_error_break to debug
```

could be reproduced with following tilelang script:
```
import tilelang
print("Imported tilelang")
from tilelang import tvm as tvm
from time import sleep
# import tilelang.testing
import tilelang.language as T
import json
import torch
import os
print("Imports done", flush=True)


from tilelang.engine.callback import register_metal_postproc_callback

@register_metal_postproc_callback
def _p(code, target):
    print(code)
    return code


@tilelang.jit
def matmul(M, N, K, block_M, block_N, block_K, dtype="float32", accum_dtype="float"):

    @T.prim_func
    def gemm(
            A: T.Tensor((M, K), dtype),
            B: T.Tensor((K, N), dtype),
            C: T.Tensor((M, N), dtype),
    ):
        with T.Kernel(
                T.ceildiv(N, block_N), T.ceildiv(M, block_M), threads=128) as (
                    bx,
                    by,
                ):
            A_shared = T.alloc_shared((block_M, block_K), dtype, scope="shared")
            B_shared = T.alloc_shared((block_K, block_N), dtype, scope="shared")
            C_local = T.alloc_fragment((block_M, block_N), accum_dtype)

            T.clear(C_local)

            for ko in T.Pipelined(T.ceildiv(K, block_K), num_stages=0):
                T.copy(A[by * block_M, ko * block_K], A_shared)
                T.copy(B[ko * block_K, bx * block_N], B_shared)

                for i, j in T.Parallel(block_M, block_N):
                    for k in T.Serial(block_K):
                        C_local[i, j] += A_shared[i, k] * B_shared[k, j]

            T.copy(C_local, C[by * block_M, bx * block_N])

    return gemm


def benchmark(f, n, *args, **kwargs):
    # trigger jit
    f(*args, **kwargs)

    torch.mps.synchronize()
    with torch.mps.profiler.profile(mode="interval,event", wait_until_completed=True):
        start = torch.mps.Event(enable_timing=True)
        end = torch.mps.Event(enable_timing=True)
        start.record()

        for _ in range(n):
            f(*args, **kwargs)

        end.record()

        start.synchronize()
        end.synchronize()

        return start.elapsed_time(end) / 1000


if __name__ == "__main__":
    m = n = k = 128
    torch_dtype = torch.float16
    dtype = 'float16'

    a = torch.randn(m, k, device="mps", dtype=torch_dtype)
    b = torch.randn(k, n, device="mps", dtype=torch_dtype)
    c = torch.zeros(m, n, device="mps", dtype=torch_dtype)

    # torch_add = lambda: torch.matmul(a, b, out=c)
    # torch_add()
    # print(benchmark(torch_add, n=100))

    print("Starting compilation...", flush=True)
    jit_kernel = matmul(m, n, k, 16, 16, 16, dtype=dtype, accum_dtype="float")
    print("Compilation finished.", flush=True)

    # print(jit_kernel.get_kernel_source())
    jit_kernel(a, b, c)
    print(c)
    print(a @ b)

```

**Comment by oraluben** [comment]
bisected to https://github.com/apache/tvm-ffi/commit/4c712ca3ec72ad18c10e42e5ef8b7f91ec23a803

Also FYI, during bisecting, there's a new behavior.

"good": exit with error message
"bad": crash

new: exited without error or crash, and result is empty (hooks not registered, kernel not run). seems to have issue between tvm and tvm-ffi. This behavior is introduced in https://github.com/apache/tvm-ffi/commit/71bbe91737afd58a330c735369c069317f48cc29 and suppressed by https://github.com/apache/tvm-ffi/commit/4c712ca3ec72ad18c10e42e5ef8b7f91ec23a803

**Comment by tqchen** [comment]
unfortunately i am not able to repro with the script on my local mac env, the code stops around 
```
RuntimeError: Compilation error:
/var/folders/1n/kv6v12_10l11p9b41lwl7q380000gn/T/tmpojumniir/lib0.c:3:10: fatal error: 'tvm/runtime/base.h' file not found
    3 | #include "tvm/runtime/base.h"
```



I have some guess and it may have to do with the tvm's version sync with tvm-ffi as tvm uses more of tvm-ffi's feature besides the C ABI, so syncing tvm's dep to latest tvm-ffi might help, we just did that in our last bump

**Comment by oraluben** [comment]
This still present in my env, I'll try to dig into this when I have time.

**Comment by oraluben** [comment]
## Root cause identified

Crash happens in `SimpleObjAllocator::Handler<ErrorObjFromStd>::Deleter_` called from `TVMFFIObjectDecRef` during Python exception cleanup (`BaseException_dealloc` → `dict_dealloc`).

**Crash detail** (from macOS arm64 crash report):
- Signal: SIGBUS (`EXC_ARM_DA_ALIGN`)
- Fault address: `0x6c616e7265746e49` = ASCII `"Internal"` (first 8 bytes of "InternalError" error kind)

The `ErrorObj` constructor (line 68-71 of error.h) sets `cause_chain = nullptr` and `extra_context = nullptr`, but on macOS arm64 the allocator (`AlignedAlloc` → `std::malloc`) may reuse memory containing stale non-null bytes. The base class constructor body may not overwrite these bytes under certain compiler optimization scenarios.

When `~ErrorObj()` runs during cleanup, it reads `cause_chain` which is NOT nullptr (contains garbage "Internal"), then calls `DecRefObjectHandle` on this garbage pointer → SIGBUS.

**Why 0.1.7 works, 0.1.8+ crashes**: PR #396 added `cause_chain` and `extra_context` fields to `ErrorObj` with a non-trivial destructor that calls `DecRefObjectHandle`. Before this, `ErrorObj` had no destructor and no such fields.

**POC fix**: #592 — explicitly zero `cause_chain` and `extra_context` in `SafeCallContext::SetRaised` / `SetRaisedByCstr` before storing the ErrorObj in TLS. This prevents the destructor from attempting `DecRefObjectHandle` on garbage pointers.

The ideal fix would be to ensure memory is zeroed at the allocator level or that the constructor reliably initializes all fields regardless of compiler optimizations. Feedback welcome.

**Comment by tqchen** [comment]
moving to this thread, i think the latest code https://github.com/apache/tvm-ffi/blob/main/include/tvm/ffi/error.h#L69 already ensures the two fields are set to zero. so updating tvm-ffi to latest should resolve the issue. 

I don't think compiler optimization will cause the issue to be set to not null.  My guess is that the issue maybe caused by tvm-ffi inconsistency in the tilelang tvm-ffi used by the tvm and the one. So a better approach is to upgrade the tvm-ffi dep to latest(the latest tvm already did that)
